dist: xenial

language: generic

cache:
  directories:
    - "$HOME/.stack"

addons:
  apt:
    packages:
      - libgmp-dev           # required by cabal

before_install:
- mkdir -p "$HOME/.local/bin"
- export PATH="$HOME/.local/bin:$PATH"
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack  --no-terminal exec site build

after_success:
- openssl aes-256-cbc
  -K $encrypted_807b3344b921_key
  -iv $encrypted_807b3344b921_iv
  -in deploy-key.enc
  -out deploy-key
  -d
- chmod 600 deploy-key
- eval $(ssh-agent -s)
- ssh-add deploy-key
- cd _site
- echo "perio.do" > CNAME
- rm -rf .git
- git init
- git add .
- git config user.name "Travis CI"
- git config user.email "nobody@travis-ci.com"
- git commit -m "Generated on $(date)"
- git remote add origin "git@github.com:periodo/periodo-website.git"
- git push -f origin master:master
