language: haskell
branches:
  only:
    - source
env:
  global:
    - secure: "CD8TwhPJLnhiFI+yHrxgdQfiBJkcmdxofSjrKlWJV6IbHPsBVoeheU/Lp3ufhZkFCVh4a1hBhw0dmRriSgKnJS6/Rap5M436BgDnxiWavznleTKSLTeyc41mr6MxXHlYgPA9MwEwJjOuE/QRCgSi+uExIbDZYmW8MFNnYCDEKmY="
install:
  - cabal install -j pandoc -fhttps
  - cabal install -j hakyll --max-backjumps=-1
  - ghc --make site.hs
before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..
script: ./site build
after_script:
  - cd _site
  - git status
  - git add --all
  - git config --global user.email "ryanshaw@unc.edu"
  - git config --global user.name "Travis CI"
  - git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
  - git push "$REPO_URL" master | grep -v http
  - cd ..
