# Enable virtual machine node, not container
sudo: true

language: haskell

cache:
  directories:
    - "$HOME/.stack"
    - "$HOME/build/periodo/periodo-website/.stack-work"

addons:
  apt:
    sources:
      - sourceline: 'ppa:hvr/ghc' # PPA of Haskell packages
    packages:
      - libgmp-dev           # required by cabal
      - cabal-install-2.0    # required by GHC 8.x

ghc:
  - 7.10

git:
  depth: 5

before_install:
- mkdir -p "$HOME/.local/bin"
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C "$HOME/.local/bin" '*/stack'
- export PATH="$HOME/.local/bin:$PATH"
- stack --version

install:
- travis_wait 30 stack setup --no-terminal
- stack ghc -- --version
- travis_wait 40 stack build --only-dependencies --no-terminal
- travis_wait 40 stack build --no-terminal

script:
- travis_wait 40 stack exec site build --no-terminal 

after_success:
- openssl aes-256-cbc
  -K $encrypted_807b3344b921_key
  -iv $encrypted_807b3344b921_iv
  -in deploy-key.enc
  -out deploy-key
  -d
- chmod 600 deploy-key
- eval $(ssh-agent -s)
- ssh-add deploy-key
- cd _site
- echo "perio.do" > CNAME
- rm -rf .git
- git init
- git add .
- git config user.name "Travis CI"
- git config user.email "nobody@travis-ci.com"
- git commit -m "Generated on $(date)"
- git remote add origin "git@github.com:periodo/periodo-website.git"
- git push -f origin master:master
